- hosts: webservers
  user: fameal
  become: true
  vars:
    dest_dir: /home/fameal/html
  tasks:
  - name: Check Node.js repository version
    shell: yum info nodejs | grep -e "Version\s*:\s*[6-9].*$"
    register: nodejs_repository_version
    check_mode: no
    changed_when: false
    failed_when: false
  - name: Register Node.js repository
    shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
    when: nodejs_repository_version.stdout == ""
  - name: Install Node.js, git, nginx
    yum: name={{ item }} state=present
    with_items:
    - nodejs
    - git
    - http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    - nginx
  - name: remove fameal project
    file:
        path: "{{ dest_dir }}"
        state: absent
  - name: get fameal project from git
    git:
        repo: https://github.com/chanfuku/fameal_nj.git
        dest: "{{ dest_dir }}"
  - name: install modules
    shell: cd {{ dest_dir }} && npm install
  - name: set env file
    copy:
        src: ../.env
        dest: "{{ dest_dir }}"
  - name: boot fameal app
    shell: cd {{ dest_dir }} && npm run build && bash start_fameal.sh
  - name: copy nginx.conf
    copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
  - name: set autoload nginx
    command: systemctl enable nginx
  - name: restart nginx
    command: systemctl restart nginx
