- hosts: targets
  connection: local
  user: vagrant
  become: yes
  tasks:
    - name: yum_install_packages
      yum: name={{ item }} state=present
      with_items:
      - epel-release
      - nodejs
      - npm
    - name: install modules
      command: cd /vagrant/ && npm install
    - name: boot fameal app
      shell: cd /vagrant/ && node node_modules/nodemon/bin/nodemon.js index.js -L -e js,ect
